name: certificate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.3
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  excel: ^4.0.6
  file_picker: ^10.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-SemiBold.ttf
  #   - family: LazyDog
  #     fonts:
  #       - asset: fonts/lazy_dog.ttf
